DHDoiSim/Controllers/UploadCMTTruocPhieuDaKhoaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DHDoiSim.Common;
using DHDoiSim.Models;


namespace DHDoiSim.Controllers
{
    public class UploadCMTTruocPhieuDaKhoaController : Controller
    {
        //User user = new User();
        DHDoiSimEntities db = new DHDoiSimEntities();
        // GET: UploadCMTTruocPhieuDaKhoa
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public ActionResult UploadFile(int? id)
        {
            ViewBag.ID_Sim_Phieu = id.ToString();
            return View();
        }
        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file, string idsp)
        {
            try
            {
                if (file.ContentLength > 0)
                {
                    string _FileName = Path.GetFileName(file.FileName);
                    string _path = Path.Combine(Server.MapPath("~/UploadedFiles"), _FileName);
                    file.SaveAs(_path);

                    var update = (from x in db.Sim_Phieu where x.ID.ToString() == idsp select x).Single();
                    update.Image_CMT_Truoc = _FileName;
                    db.SaveChanges();
                }

                ViewBag.Message = "File Uploaded Successfully!idsp = " + idsp.ToString();
                //return View();
                return RedirectToAction("../NhanKhoaPhieu/UpdatPhieuDaKhoa/" + idsp);
                //< a href = "/DHDoiSim/NhanKhoaPhieu/EditKhoaPhieu/@item.ID
            }
            catch
            {
                ViewBag.Message = "File upload failed!!";
                return View();
            }
        }
    }
}

DHDoiSim/Views/UploadCMTTruocPhieuDaKhoa/UploadFile.cshtml
@{
    ViewBag.Title = "UploadFile";
}

<h2>Upload CMT Mặt trước</h2>
<h4>ID Sim phiếu @ViewBag.ID_Sim_Phieu</h4>
@using (Html.BeginForm("UploadFile", "UploadCMTTruocPhieuDaKhoa", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        @Html.TextBox("file", "", new { type = "file" }) <br />
        @Html.TextBox("idsp", (string)ViewBag.ID_Sim_Phieu, new { type = "string", @readonly = "readonly", @hidden = "true" }) <br />
        @*<input type="text" id="idsp" value = @ViewBag.ID_Sim_Phieu />*@
        <input type="submit" value="Upload" />
        @ViewBag.Message
    </div>
}