DHDoiSim/Controllers/OutBoundController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DHDoiSim.Models;
using PagedList;
using DHDoiSim.Common;
using System.Data.Entity.Validation;
using System.Data.OleDb;

namespace DHDoiSim.Controllers
{
    public class OutBoundController : Controller
    {
        private DHDoiSimEntities db = new DHDoiSimEntities();
        User user = new User();
        OutBoundDA Model = new OutBoundDA();

        //GET: OutBound
        //Gốc
        //public ActionResult Index()
        //{
        //    var sim_KH = db.Sim_KH.Include(s => s.DMDonViKT).Include(s => s.DMKetQuaThucHien).Include(s => s.DMStatusOBKH);
        //    return View(sim_KH.ToList());
        //}

        public ActionResult Index(int? page, int? pageSize, string Ten_QH,string Ten_Phong, string ID_StatusOB, string ID_KetQuaThucHien, string NguoiGoi, string SoDT, int? isSendSMS, int? TapKH)
        {
            //ThaiHN thêm
            if (Session[UserSession.ISLOGIN] == null || !(bool)Session[UserSession.ISLOGIN])
                return RedirectToAction("Index", "Login");

            if (user.PERMISSION > 5)
                return RedirectToAction("Index", "Login");

            Model.UpdateLastLogin();
            Model.UpdateLastSeen("Gọi OutBound", Url.Action("Index"));

            List<SelectListItem> list = new List<SelectListItem>();
            //var Ten_QH = (from c in db.Sim_KH select c).ToArray();
            var aTen_QH = db.Sim_KH.Where(x => x.Ten_QH != null).OrderBy(x => x.Ten_QH).Select(x => x.Ten_QH).Distinct().ToArray();
            for (int i = 0; i < aTen_QH.Length; i++)
            {
                list.Add(new SelectListItem
                {
                    Text = aTen_QH[i].ToString(),
                    Value = aTen_QH[i].ToString(),
                });
            }
            list.Add(new SelectListItem { Text = "Tất cả", Value = "all", Selected = true });
            ViewData["DSQuanHuyen"] = list;

            //Phòng
            List<SelectListItem> listphong = new List<SelectListItem>();
            //var Ten_QH = (from c in db.Sim_KH select c).ToArray();
            var aTen_Phong = db.Sim_KH.Where(x => x.GhiChu3 != null).OrderBy(x => x.GhiChu3).Select(x => x.GhiChu3).Distinct().ToArray();
            for (int i = 0; i < aTen_Phong.Length; i++)
            {
                listphong.Add(new SelectListItem
                {
                    Text = aTen_Phong[i].ToString(),
                    Value = aTen_Phong[i].ToString(),
                });
            }
            listphong.Add(new SelectListItem { Text = "Tất cả", Value = "all", Selected = true });
            ViewData["DSPhong"] = listphong;

            //set viewbag value
            ViewBag.Ten_QH = Ten_QH ?? "all";
            ViewBag.Ten_Phong = Ten_Phong ?? "all";

            //ViewBag.ID_StatusOB = ID_StatusOB ?? "all";
            //ViewBag.ID_KetQuaThucHien = ID_KetQuaThucHien ?? "all";
            ViewBag.ID_StatusOB = ID_StatusOB ?? "all";
            ViewBag.ID_KetQuaThucHien = ID_KetQuaThucHien ?? "all";
            ViewBag.NguoiGoi = NguoiGoi ?? "all";
            ViewBag.SoDT = SoDT ?? "";
            ViewBag.isSendSMS = isSendSMS ?? 1;
            ViewBag.TapKH = TapKH ?? 1;

            List<SelectListItem> list2 = new List<SelectListItem>();

            var aStatusOB = db.DMStatusOBKHs.ToList();
            for (int i = 0; i < aStatusOB.Count(); i++)
            {
                if (aStatusOB[i].ID == 1)
                    list2.Add(new SelectListItem
                    {
                        Text = aStatusOB[i].StatusName.ToString(),
                        Value = aStatusOB[i].ID.ToString(),
                        Selected = true,
                    });
                else
                    list2.Add(new SelectListItem
                    {
                        Text = aStatusOB[i].StatusName.ToString(),
                        Value = aStatusOB[i].ID.ToString(),
                    });
            }
            list2.Add(new SelectListItem { Text = "Tất cả", Value = "all"});
            ViewData["DSTrangThai"] = list2;

            List<SelectListItem> list3 = new List<SelectListItem>();

            var aKetQuaThucHien = db.DMKetQuaThucHiens.ToList();
            for (int i = 0; i < aKetQuaThucHien.Count(); i++)
            {
                if (aKetQuaThucHien[i].ID == 1)
                    list3.Add(new SelectListItem
                    {
                        Text = aKetQuaThucHien[i].StatusName.ToString(),
                        Value = aKetQuaThucHien[i].ID.ToString(),
                        Selected = true,
                    });
                else
                    list3.Add(new SelectListItem
                    {
                        Text = aKetQuaThucHien[i].StatusName.ToString(),
                        Value = aKetQuaThucHien[i].ID.ToString(),
                    });
            }
            list3.Add(new SelectListItem { Text = "Tất cả", Value = "all"});
            ViewData["DSKetQuaThucHien"] = list3;

            //Người gọi
            List<SelectListItem> listnguoigoi = new List<SelectListItem>();
            var aNguoiGoi = db.Sim_KH.Where(x => x.NguoiGoi != null).OrderBy(x => x.NguoiGoi).Select(x => x.NguoiGoi).Distinct().ToArray();
            for (int i = 0; i < aNguoiGoi.Length; i++)
            {
                listnguoigoi.Add(new SelectListItem
                {
                    Text = aNguoiGoi[i].ToString(),
                    Value = aNguoiGoi[i].ToString(),
                });
            }
            listnguoigoi.Add(new SelectListItem { Text = "Tất cả", Value = "all", Selected = true });
            ViewData["DSNguoiGoi"] = listnguoigoi;

            if (pageSize == null)
            {
                pageSize = 200;
            }

            int pageIndex = 1;
            ViewBag.Page = page == null ? "1" : page.ToString();
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;

            IPagedList<Sim_KH> simkh = null;
            //var Theo_Doi_Vat_Tu = db.So_Theo_Doi_Vat_Tu.Include(s => s.DM_Nguon_Tai_San).Include(s => s.DM_Vat_Tu_Chi_Tiet).Include(s => s.DM_TinhTrangVT).Include(s => s.Thiet_Bi);

            var sim_KHs = db.Sim_KH.Include(s => s.DMDonViKT).Include(s => s.DMStatusOBKH).Where(x => x.ID > 0);

            if (!String.IsNullOrEmpty(Ten_QH) && Ten_QH.ToString() != "all")
            {
                sim_KHs = sim_KHs.Where(x => x.Ten_QH.ToString() == Ten_QH.Trim());
            }

            if (!String.IsNullOrEmpty(Ten_Phong) && Ten_Phong.ToString() != "all")
            {
                sim_KHs = sim_KHs.Where(x => x.GhiChu3.ToString() == Ten_Phong.Trim());
            }

            if (!String.IsNullOrEmpty(ID_StatusOB) && ID_StatusOB.ToString() != "all")
            {
                sim_KHs = sim_KHs.Where(x => x.ID_StatusOBKH.ToString() == ID_StatusOB.Trim());
            }

            if (!String.IsNullOrEmpty(ID_KetQuaThucHien) && ID_KetQuaThucHien.ToString() != "all")
            {
                sim_KHs = sim_KHs.Where(x => x.ID_KetQuaThucHien.ToString() == ID_KetQuaThucHien.Trim());
            }

            if (!String.IsNullOrEmpty(NguoiGoi) && NguoiGoi.ToString() != "all")
            {
                sim_KHs = sim_KHs.Where(x => x.NguoiGoi.ToString() ==NguoiGoi.Trim());
            }

            if (!String.IsNullOrEmpty(SoDT) && SoDT.ToString() != "")
            {
                sim_KHs = sim_KHs.Where(s => s.SoDT == SoDT.Trim());
            }

            if (String.IsNullOrEmpty(Ten_QH) && String.IsNullOrEmpty(ID_StatusOB) && String.IsNullOrEmpty(ID_KetQuaThucHien) && String.IsNullOrEmpty(NguoiGoi) && String.IsNullOrEmpty(SoDT))
                sim_KHs = sim_KHs.Where(s => s.ID == -1);
            if(isSendSMS == 1) {
                sim_KHs = sim_KHs.Where(x => x.isSendSMS == 1);
            }
            else
            {
                sim_KHs = sim_KHs.Where(x => x.isSendSMS != 1);
            }
            if (TapKH == 1)
            {
                sim_KHs = sim_KHs.Where(x => x.ID_DonViKT == 1);
            }
            if (TapKH == 2)
            {
                sim_KHs = sim_KHs.Where(x => x.ID_DonViKT == 2);
            }
            if (TapKH == 0)
            {
                sim_KHs = sim_KHs.Where(x => x.ID_DonViKT != 1 && x.ID_DonViKT != 2);
            }
            simkh = sim_KHs.OrderByDescending(s => s.Ten_QH).ToPagedList(pageIndex, pageSize ?? 50);
            return View(simkh);

            //Hết thêm 
            //return View(sim_KHs.ToList());
        }

        //ThaiHN thêm
        public ActionResult TraCuu(int? page, int? pageSize, string Ten_QH, string Ten_Phong, string Ten_Phong_NP, string ID_StatusOB, string ID_KetQuaThucHien, string NguoiGoi, string SoDT)
        {
            //ThaiHN thêm
            if (Session[UserSession.ISLOGIN] == null || !(bool)Session[UserSession.ISLOGIN])
                return RedirectToAction("Index", "Login");

            if (user.PERMISSION > 8)
                return RedirectToAction("Index", "Login");

            Model.UpdateLastLogin();
            Model.UpdateLastSeen("Tra cứu kết quả OutBound", Url.Action("TraCuu"));

            List<SelectListItem> list = new List<SelectListItem>();
            //var Ten_QH = (from c in db.Sim_KH select c).ToArray();
            var aTen_QH = db.Sim_KH.Where(x => x.Ten_QH != null).OrderBy(x => x.Ten_QH).Select(x => x.Ten_QH).Distinct().ToArray();
            for (int i = 0; i < aTen_QH.Length; i++)
            {
                list.Add(new SelectListItem
                {
                    Text = aTen_QH[i].ToString(),
                    Value = aTen_QH[i].ToString(),
                });
            }
            list.Add(new SelectListItem { Text = "Tất cả", Value = "all", Selected = true });
            ViewData["DSQuanHuyen"] = list;

DHDoiSim/Views/OutBound/Delete.cshtml
@model DHDoiSim.Models.Sim_KH

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Sim_KH</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.SoDT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SoDT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Loai_TB)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Loai_TB)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BTS_Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BTS_Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dia_Chi_BTS)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dia_Chi_BTS)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Don_Vi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Don_Vi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TTVT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TTVT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dia_Chi_BTS2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dia_Chi_BTS2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phuong_Xa_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phuong_Xa_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quan_Huyen_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quan_Huyen_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ve_Tinh_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ve_Tinh_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TenPhong)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TenPhong)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ten_TT)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_TT)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ten_QH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_QH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ten_PX)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_PX)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Doi_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Doi_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ten_Doi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ten_Doi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TT_ID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TT_ID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TimeUpFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TimeUpFile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UserUpFile)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UserUpFile)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Timestamps)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Timestamps)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NguoiGoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NguoiGoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioGoi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioGoi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GioHen)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GioHen)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DiaChiHenDoiSim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DiaChiHenDoiSim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LyDoPhanDiaBan)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LyDoPhanDiaBan)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TieuChi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TieuChi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu1)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu1)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GhiChu3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GhiChu3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DMDonViKT.TenDonVi)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMDonViKT.TenDonVi)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DMKetQuaThucHien.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMKetQuaThucHien.StatusName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DMStatusOBKH.StatusName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DMStatusOBKH.StatusName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DHDoiSim/Views/OutBound/Index.cshtml
@*@model IEnumerable<DHDoiSim.Models.Sim_KH>*@
@model PagedList.IPagedList<DHDoiSim.Models.Sim_KH>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
}

<h2>OutBound & Xuất phiếu</h2>

<p>
    @Html.ActionLink("Create Thuê bao mới", "CreateThueBaoMoi")
</p>

@*ThaiHN thêm*@
@using (Html.BeginForm("Index", "OutBound", FormMethod.Get))
{
    <div class="row">
        <div class="col-md-2">
            Quận/Huyện
        </div>

        <div class="col-md-2">
            @Html.DropDownList("Ten_QH", (IEnumerable<SelectListItem>)ViewData["DSQuanHuyen"],
            new { onchange = "OnOutBoundChange(this.value)" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            Phòng theo địa chỉ BTS
        </div>
        <div class="col-md-2">
            @Html.DropDownList("Ten_Phong", (IEnumerable<SelectListItem>)ViewData["DSPhong"],
            new { onchange = "OnOutBoundChange(this.value)" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            Trạng thái OutBound
        </div>

        <div class="col-md-2">
            @Html.DropDownList("ID_StatusOB", (IEnumerable<SelectListItem>)ViewData["DSTrangThai"],
            new { onchange = "OnOutBoundChange(this.value)" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            Kết quả thực hiện
        </div>

        <div class="col-md-2">
            @Html.DropDownList("ID_KetQuaThucHien", (IEnumerable<SelectListItem>)ViewData["DSKetQuaThucHien"],
            new { onchange = "OnOutBoundChange(this.value)" })
        </div>
    </div>

    <div class="row">
        <div class="col-md-2">
            Người gọi
        </div>

        <div class="col-md-2">
            @Html.DropDownList("NguoiGoi", (IEnumerable<SelectListItem>)ViewData["DSNguoiGoi"],
            new { onchange = "OnOutBoundChange(this.value)" })
        </div>
    </div>


    <div class="row">

        <div class="col-md-2">
            Số Điện thoại
        </div>

        <div class="col-md-2">
            @Html.TextBox("SoDT", "", new { style = "color:red" })
        </div>

        <div class="col-md-3">
            <button type="submit" class="btn btn-info">
                <span class="glyphicon glyphicon-search"></span>
                <span class="submit-text">&nbsp;&nbsp;Tìm</span>
            </button>
        </div>

    </div>
}
@*Hết thêm*@
<table class="table">
    <tr>
        <th>STT</th>

        <th>
            Giữ/Bỏ giữ
        </th>

        <th>
            Nhập kết quả OutBound
        </th>

        <th>
            Xuất phiếu
        </th>

        <th>
            Số ĐT
            @*@Html.DisplayNameFor(model => model.SoDT)*@
        </th>

        <th>
            Kết quả OutBound
            @*@Html.DisplayNameFor(model => model.DMStatusOBKH.StatusName)*@
        </th>

        <th>
            Kết quả thực hiện
            @*@Html.DisplayNameFor(model => model.DMKetQuaThucHien.StatusName)*@
        </th>

        <th>
            Tên Phòng theo đ/c hẹn đổi Sim
            @*@Html.DisplayNameFor(model => model.TenPhong)*@
        </th>

        <th>
            Giờ hẹn
            @*@Html.DisplayNameFor(model => model.GioHen)*@
        </th>

        <th>
            Địa chỉ hẹn đồi Sim
            @*@Html.DisplayNameFor(model => model.DiaChiHenDoiSim)*@
        </th>
        <th>
            Quận huyện hẹn đồi Sim
            @*@Html.DisplayNameFor(model => model.QHHenDoiSim)*@
        </th>
        <th>
            Phường xã hẹn đồi Sim
            @*@Html.DisplayNameFor(model => model.PXHenDoiSim)*@
        </th>

        <th>
            Người gọi
            @*@Html.DisplayNameFor(model => model.NguoiGoi)*@
        </th>
        <th>
            Giờ gọi
            @*@Html.DisplayNameFor(model => model.GioGoi)*@
        </th>
        <th>
            Ghi chú
        </th>
        <th>
            Tên phòng theo phân vùng BTS
        </th>
        <th>
            Tên Quận Huyện
        </th>
        <th>
            Tên Phường Xã
        </th>

        @*<th>
                Loại TB
            </th>
            <th>
                BTS name
            </th>
            <th>
                Code
            </th>
            <th>
                Model
            </th>
            <th>
                Địa chỉ BTS
            </th>
            <th>
                Đơn vị
            </th>
            <th>
                TTVT
            </th>
            <th>
                Địa chỉ BTS2
            </th>
            <th>
                ID Phường xã
            </th>
            <th>
                ID Quận Huyện
            </th>
            <th>
                ID Vệ tinh
            </th>
            <th>
                Trên TTVT
            </th>
            <th>
                ID Phường Xã
            </th>
            <th>
                Tên Đội
            </th>
            <th>
                ID TT
            </th>
            <th>
                TimeUpdate
            </th>
            <th>
                UserUpdate
            </th>
            <th>
                Timestamps
            </th>
            <th>
                LyDoPhanDiaBan
            </th>
            <th>
                TieuChi
            </th>
            <th>
                GhiChu1
            </th>
            <th>
                GhiChu2
            </th>*@
        <th></th>
    </tr>

    @{int rowNo = 0;}
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @(rowNo += 1)
            </td>

            <td>
                <a href="@Url.Action("ToggleStatus/" + item.ID)">Giữ/Bỏ giữ</a><br />
            </td>

            <td>
                @if (@item.ID_KetQuaThucHien != 2 && @item.ID_KetQuaThucHien != 3)
                {
                    <a href="/OutBound/EditOutBound/@item.ID " class="btn btn-primary" title="Nhập kết quả OutBound">
                        <span class="glyphicon glyphicon-phone"></span>
                    </a>
                }
            </td>

            <td>
                @if (@item.ID_StatusOBKH == 3 && @item.ID_KetQuaThucHien == 1 && @item.GioHen != null && !String.IsNullOrEmpty(@item.TenPhong) && !String.IsNullOrEmpty(@item.DiaChiHenDoiSim) && !String.IsNullOrEmpty(@item.QHHenDoiSim) && !String.IsNullOrEmpty(@item.PXHenDoiSim))
                {
                    <a href="/NhanKhoaPhieu/Create/@item.ID " class="btn btn-primary" title="Xuất phiếu">
                        <span class="glyphicon glyphicon-arrow-right"></span>
                    </a>
                }
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.SoDT)
            </td>

            <td>
                <font color="#FF0000">
                    @Html.DisplayFor(modelItem => item.DMStatusOBKH.StatusName)
                </font>
            </td>

            <td>
                <font color="#FF0000">
                    @Html.DisplayFor(modelItem => item.DMKetQuaThucHien.StatusName)
                </font>
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.TenPhong)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.GioHen)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.DiaChiHenDoiSim)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.QHHenDoiSim)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.PXHenDoiSim)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.NguoiGoi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GioGoi)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.GhiChu)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GhiChu3)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten_QH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ten_PX)
            </td>

            @*<td>
                    @Html.DisplayFor(modelItem => item.Loai_TB)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BTS_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Model)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dia_Chi_BTS)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Don_Vi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TTVT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Dia_Chi_BTS2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Phuong_Xa_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quan_Huyen_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ve_Tinh_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ten_TT)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Doi_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Ten_Doi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TT_ID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TimeUpFile)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserUpFile)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Timestamps)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LyDoPhanDiaBan)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TieuChi)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GhiChu1)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.GhiChu2)
                </td>*@
            <td>
                @*@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |*@
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @*@Html.ActionLink("Delete", "Delete", new { id = item.ID })*@
            </td>
        </tr>
    }

</table>
<br />

@*ThaiHN thêm*@
<div id='Paging' style="text-align:center">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)
    of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, Ten_QH = ViewBag.Ten_QH, Ten_Phong = ViewBag.Ten_Phong, ID_StatusOB = ViewBag.ID_StatusOB, ID_KetQuaThucHien = ViewBag.ID_KetQuaThucHien, NguoiGoi = ViewBag.NguoiGoi }))
</div>
@*Hết thêm*@